### ISSUE TITLE
Crash at start parsing json

### ISSUE THREAD

**Issue by brarcher** [martykan/forecastie#102]
This morning the Forcastie app v1.0 from F-Droid was unable to run, perhaps due to unexpected data arriving from OpenWeatherMap.

Here is the exception which brought down the app: 
```
E/AndroidRuntime(17172): FATAL EXCEPTION: AsyncTask #4
E/AndroidRuntime(17172): Process: cz.martykan.forecastie, PID: 17172
E/AndroidRuntime(17172): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(17172): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime(17172): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(17172): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(17172): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(17172): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(17172): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(17172): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(17172): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(17172): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.getString(java.lang.String)' on a null object reference
E/AndroidRuntime(17172): 	at cz.martykan.forecastie.MainActivity.parseLongTermJson(MainActivity.java:475)
E/AndroidRuntime(17172): 	at cz.martykan.forecastie.MainActivity$LongTermWeatherTask.parseResponse(MainActivity.java:898)
E/AndroidRuntime(17172): 	at cz.martykan.forecastie.MainActivity$GenericRequestTask.doInBackground(MainActivity.java:790)
E/AndroidRuntime(17172): 	at cz.martykan.forecastie.MainActivity$GenericRequestTask.doInBackground(MainActivity.java:712)
E/AndroidRuntime(17172): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime(17172): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(17172): 	... 4 more
```

**Comment by martykan** [comment]
Yep, it's due to wind sometimes being null now. Fix is already coming with 1.1 today.
