### ISSUE TITLE
Crash when adding Widget

### ISSUE THREAD

**Issue by Nutomic** [martykan/forecastie#122]
I just got this crash on a fresh install. Steps to reproduce:

1. Install Forecastie
2. Do not start Forecastie
3. Add widget to homescreen

```
FATAL EXCEPTION: main
Process: cz.martykan.forecastie, PID: 13594
Theme: themes:{}
java.lang.RuntimeException: Unable to start receiver cz.martykan.forecastie.widgets.TimeWidgetProvider: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2766)
    at android.app.ActivityThread.-wrap14(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
    at android.graphics.Canvas.drawText(Canvas.java:1656)
    at cz.martykan.forecastie.widgets.AbstractWidgetProvider.getWeatherIcon(AbstractWidgetProvider.java:41)
    at cz.martykan.forecastie.widgets.TimeWidgetProvider.onUpdate(TimeWidgetProvider.java:57)
    at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:66)
    at cz.martykan.forecastie.widgets.TimeWidgetProvider.onReceive(TimeWidgetProvider.java:72)
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2759)
    at android.app.ActivityThread.-wrap14(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5461) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by martykan** [comment]
Fix commited in 790c0cd. It will make the app start first, when your crash scenario is about to happen.

**Comment by martykan** [comment]
Oh, this is the one you were talking about in #112, right?

**Comment by Nutomic** [comment]
No #112 is a seperate issue, which still happens after the first start.
