### ISSUE TITLE
Widget stops getting updated

### ISSUE THREAD

**Issue by Nutomic** [martykan/forecastie#124]
After some time, the widget stops getting updated. This might be because I walk around and lose internet connection at some point, but I don't know the exact cause. The end result is that the time widget gets stuck on an old time, and starting the app gives the following crash log:

```
08-14 23:42:18.216 31144 31144 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
08-14 23:42:18.216 31144 31144 E AndroidRuntime:        at cz.martykan.forecastie.activities.MainActivity.updateTodayWeatherUI(MainActivity.java:414)
08-14 23:42:18.216 31144 31144 E AndroidRuntime:        at cz.martykan.forecastie.activities.MainActivity.access$200(MainActivity.java:77)
08-14 23:42:18.216 31144 31144 E AndroidRuntime:        at cz.martykan.forecastie.activities.MainActivity$TodayWeatherTask.updateMainUI(MainActivity.java:830)
08-14 23:42:18.216 31144 31144 E AndroidRuntime:        at cz.martykan.forecastie.tasks.GenericRequestTask.onPostExecute(GenericRequestTask.java:131)
08-14 23:42:18.216 31144 31144 E AndroidRuntime:        at cz.martykan.forecastie.activities.MainActivity$TodayWeatherTask.onPostExecute(MainActivity.java:812)
08-14 23:42:18.216 31144 31144 E AndroidRuntime:        at cz.martykan.forecastie.activities.MainActivity$TodayWeatherTask.onPostExecute(MainActivity.java:799)
08-14 23:42:18.216 31144 31144 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:651)
08-14 23:42:18.216 31144 31144 E AndroidRuntime:        at android.os.AsyncTask.-wrap1(AsyncTask.java)
08-14 23:42:18.216 31144 31144 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
08-14 23:42:18.216 31144 31144 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
08-14 23:42:18.216 31144 31144 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
08-14 23:42:18.216 31144 31144 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5461)
08-14 23:42:18.216 31144 31144 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-14 23:42:18.216 31144 31144 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-14 23:42:18.216 31144 31144 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-14 23:42:18.220  1897  5625 W ActivityManager:   Force finishing activity cz.martykan.forecastie/.activities.MainActivity
```

Edit: This issue might be related to #112.

**Comment by martykan** [comment]
This is very strange, it's nearly an impossible scenario.
It must happen when todayWeather is not set, but it happens in the updateTodayWeatherUI function, which is only executed after todayWeather is set.

**Comment by Nutomic** [comment]
My guess is that the weather update didn't work right, because of a connection timeout or something like that. It then stored the invalid data and crashed the background service. When I start the app again, it loads the service, which attempts to read the invalid data.

**Comment by martykan** [comment]
OK, I think it should be fixed.
