### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Massedil** [martykan/forecastie#234]
I think this crash has occurred when switching off the data network.

> 08-01 01:55:28.589 W/System.err(17224): at cz.martykan.forecastie.tasks.GenericRequestTask.doInBackground(GenericRequestTask.java:77)
> 08-01 01:55:28.589 W/System.err(17224): at cz.martykan.forecastie.tasks.GenericRequestTask.doInBackground(GenericRequestTask.java:29)
> 08-01 01:55:28.616 E/AndroidRuntime(17224): Process: cz.martykan.forecastie, PID: 17224
> 08-01 01:55:28.616 E/AndroidRuntime(17224): at cz.martykan.forecastie.activities.MainActivity.updateTodayWeatherUI(MainActivity.java:420)
> 08-01 01:55:28.616 E/AndroidRuntime(17224): at cz.martykan.forecastie.activities.MainActivity.access$200(MainActivity.java:66)
> 08-01 01:55:28.616 E/AndroidRuntime(17224): at cz.martykan.forecastie.activities.MainActivity$TodayWeatherTask.updateMainUI(MainActivity.java:826)
> 08-01 01:55:28.616 E/AndroidRuntime(17224): at cz.martykan.forecastie.tasks.GenericRequestTask.onPostExecute(GenericRequestTask.java:132)
> 08-01 01:55:28.616 E/AndroidRuntime(17224): at cz.martykan.forecastie.activities.MainActivity$TodayWeatherTask.onPostExecute(MainActivity.java:808)
> 08-01 01:55:28.616 E/AndroidRuntime(17224): at cz.martykan.forecastie.activities.MainActivity$TodayWeatherTask.onPostExecute(MainActivity.java:795)
> 08-01 01:55:28.661 W/System.err(17224): at cz.martykan.forecastie.tasks.GenericRequestTask.doInBackground(GenericRequestTask.java:77)
> 08-01 01:55:28.661 W/System.err(17224): at cz.martykan.forecastie.tasks.GenericRequestTask.doInBackground(GenericRequestTask.java:29)
> 08-01 01:55:28.671 W/System.err(17224): at cz.martykan.forecastie.tasks.GenericRequestTask.doInBackground(GenericRequestTask.java:77)
> 08-01 01:55:28.671 W/System.err(17224): at cz.martykan.forecastie.tasks.GenericRequestTask.doInBackground(GenericRequestTask.java:29)
> 08-01 01:55:28.680 W/System.err(17224): at cz.martykan.forecastie.tasks.GenericRequestTask.doInBackground(GenericRequestTask.java:77)
> 08-01 01:55:28.680 W/System.err(17224): at cz.martykan.forecastie.tasks.GenericRequestTask.doInBackground(GenericRequestTask.java:29)
> 08-01 01:55:32.615 I/ActivityManager(2971): Process cz.martykan.forecastie (pid 17224) has died

**Comment by robinpaulson** [comment]
Is this repeatable, or have you only seen it once?

**Comment by Massedil** [comment]
I can't reproduce the crash. It's the first time I have seen it.

**Comment by robinpaulson** [comment]
I think this is an untrapped error which happens when the data is cut off part way through the download process. We should probably trap it and deal with it gracefully, firstly by trying again, secondly by popping up a toast with a useful error message like "The connection was closed, data cannot be downloaded".

**Comment by robinpaulson** [comment]
Maybe we should include as part of #316.

**Comment by robinpaulson** [comment]
This is more than merely updating error messages; how do we detect we have not downloaded the full payload? Is there a checksum, parity check or similar? Investigation required.
