### ISSUE TITLE
IllegalArgumentException when Android AVD does not provide ''network"

### ISSUE THREAD

**Issue by Prefest2018** [martykan/forecastie#395]
Hi, I am using my home-made automatic testing tool for forecastie (a quite old version), on the official AVD emulator of Galaxy Nexus, API 19. 

The AVD crashes when setting preference 'updateLocationAutomatically', with the call trace here :
```
E/AndroidRuntime(10298): FATAL EXCEPTION: main
E/AndroidRuntime(10298): Process: cz.martykan.forecastie, PID: 10298
E/AndroidRuntime(10298): java.lang.IllegalArgumentException: provider doesn't exist: network
E/AndroidRuntime(10298): 	at android.os.Parcel.readException(Parcel.java:1469)
E/AndroidRuntime(10298): 	at android.os.Parcel.readException(Parcel.java:1419)
E/AndroidRuntime(10298): 	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:540)
E/AndroidRuntime(10298): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:860)
E/AndroidRuntime(10298): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:454)
E/AndroidRuntime(10298): 	at cz.martykan.forecastie.activities.SettingsActivity.privacyGuardWorkaround(SettingsActivity.java:155)
E/AndroidRuntime(10298): 	at cz.martykan.forecastie.activities.SettingsActivity.requestReadLocationPermission(SettingsActivity.java:134)
E/AndroidRuntime(10298): 	at cz.martykan.forecastie.activities.SettingsActivity.onSharedPreferenceChanged(SettingsActivity.java:112)
E/AndroidRuntime(10298): 	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:475)
E/AndroidRuntime(10298): 	at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:385)
E/AndroidRuntime(10298): 	at android.preference.Preference.tryCommit(Preference.java:1372)
E/AndroidRuntime(10298): 	at android.preference.Preference.persistBoolean(Preference.java:1638)
E/AndroidRuntime(10298): 	at android.preference.TwoStatePreference.setChecked(TwoStatePreference.java:84)
E/AndroidRuntime(10298): 	at android.preference.TwoStatePreference.onClick(TwoStatePreference.java:70)
E/AndroidRuntime(10298): 	at android.preference.Preference.performClick(Preference.java:952)
E/AndroidRuntime(10298): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
E/AndroidRuntime(10298): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime(10298): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
E/AndroidRuntime(10298): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2904)
E/AndroidRuntime(10298): 	at android.widget.AbsListView$3.run(AbsListView.java:3638)
E/AndroidRuntime(10298): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(10298): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(10298): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(10298): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime(10298): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10298): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(10298): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime(10298): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime(10298): 	at dalvik.system.NativeStart.main(Native Method)
```
I search on google and find the reason lies in that forecastie is requesting updates from the network provider when that provider does not exist on the device, and I find that the problem still exists in the lastest version. Would you please fix it, such as adding a checking before the request, like https://stackoverflow.com/questions/20660561/illegalargumentexception-provider-doesnt-exisit-null-on-maps-v1 ?

**Comment by robinpaulson** [comment]
Thanks very much for this, I think this will clear up a couple of bugs.

**Comment by robinpaulson** [comment]
#349 #234

**Comment by robinpaulson** [comment]
Are you prepared to code, @prefest2018

**Comment by FridoDeluxe** [comment]
> #349 #234

I'm not sure if this IllegalArgumentException is related to internet connection bugs. Seems like `privacyGuardWorkaround()` is just used for forcing a permission request, but has nothing to do with real network access, since the `dummyLocationListener` is removed immediately. But that's just a guess from looking at the code.

**Comment by FridoDeluxe** [comment]
I can confirm this bug on a real device, with both mobile data activated and deactivated. Looks like _updateLocationAutomatically_ it doesn't work for me at all. Anybody using this feature without problems?

**Comment by igor-cali** [comment]
@FridoDeluxe I have the setting checked in my personal device (Oreo 8.0). I do not experience issues. How can I help further?

**Comment by FridoDeluxe** [comment]
This is what I got (LineageOS 16 without Google Apps, GPS deactivated, but mobile network activated):

```
java.lang.IllegalArgumentException: provider doesn't exist: network
        at android.os.Parcel.createException(Parcel.java:1954)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:755)
        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1007)
        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:561)
        at cz.martykan.forecastie.activities.SettingsActivity.privacyGuardWorkaround(SettingsActivity.java:164)
        at cz.martykan.forecastie.activities.SettingsActivity.requestReadLocationPermission(SettingsActivity.java:143)
        at cz.martykan.forecastie.activities.SettingsActivity.onSharedPreferenceChanged(SettingsActivity.java:121)
        at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:607)
        at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:489)
        at android.preference.Preference.tryCommit(Preference.java:1590)
        at android.preference.Preference.persistBoolean(Preference.java:1894)
        at android.preference.TwoStatePreference.setChecked(TwoStatePreference.java:81)
        at android.preference.TwoStatePreference.onClick(TwoStatePreference.java:66)
        at android.preference.Preference.performClick(Preference.java:1135)
        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:249)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
        at android.widget.AbsListView.onTouchUp(AbsListView.java:4064)
        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3822)
        at android.view.View.dispatchTouchEvent(View.java:12513)
        ...
```

I don't know how to solve that ...
