### ISSUE TITLE
Error parsing JSON

### ISSUE THREAD

**Issue by kowalcj0** [martykan/forecastie#41]
Recently updated Forecastie to v0.7. 
Ever since I'm getting "Error parsing JSON".
I'm running CM13.1 (Android 6.0.1) on Oppo Find 7.

```
01-28 10:00:21.936 15435-15488/? W/System.err: java.io.FileNotFoundException: http://api.openweathermap.org/data/2.5/weather?q=London&lang=en&appid=2de143494c0b295cca9337e1e96b00e0
01-28 10:00:21.936 15435-15488/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
01-28 10:00:21.936 15435-15488/? W/System.err:     at cz.martykan.forecastie.MainActivity$GetWeatherTask.doInBackground(MainActivity.java:487)
01-28 10:00:21.936 15435-15488/? W/System.err:     at cz.martykan.forecastie.MainActivity$GetWeatherTask.doInBackground(MainActivity.java:465)
01-28 10:00:21.936 15435-15488/? W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
01-28 10:00:21.936 15435-15488/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-28 10:00:21.936 15435-15488/? W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
01-28 10:00:21.936 15435-15488/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-28 10:00:21.936 15435-15488/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-28 10:00:21.936 15435-15488/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
01-28 10:00:21.940 254-254/? E/Region: Region::boolean_operation(op=7) invalid Rect={0,955,92,720}
01-28 10:00:21.940 254-254/? E/Region: Region::boolean_operation(op=7) invalid Rect={1423,955,1624,720}
01-28 10:00:21.958 15435-15435/? W/System.err: org.json.JSONException: End of input at character 0 of 
01-28 10:00:21.958 15435-15435/? W/System.err:     at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
01-28 10:00:21.958 15435-15435/? W/System.err:     at org.json.JSONTokener.nextValue(JSONTokener.java:97)
01-28 10:00:21.958 15435-15435/? W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:156)
01-28 10:00:21.958 15435-15435/? W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
01-28 10:00:21.958 15435-15435/? W/System.err:     at cz.martykan.forecastie.MainActivity.parseTodayJson(MainActivity.java:271)
01-28 10:00:21.958 15435-15435/? W/System.err:     at cz.martykan.forecastie.MainActivity.access$200(MainActivity.java:48)
01-28 10:00:21.958 15435-15435/? W/System.err:     at cz.martykan.forecastie.MainActivity$GetWeatherTask.onPostExecute(MainActivity.java:511)
01-28 10:00:21.958 15435-15435/? W/System.err:     at cz.martykan.forecastie.MainActivity$GetWeatherTask.onPostExecute(MainActivity.java:465)
01-28 10:00:21.958 15435-15435/? W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:651)
01-28 10:00:21.958 15435-15435/? W/System.err:     at android.os.AsyncTask.-wrap1(AsyncTask.java)
01-28 10:00:21.958 15435-15435/? W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
01-28 10:00:21.958 15435-15435/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-28 10:00:21.958 15435-15435/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
01-28 10:00:21.959 15435-15435/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5466)
01-28 10:00:21.959 15435-15435/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-28 10:00:21.959 15435-15435/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-28 10:00:21.959 15435-15435/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-28 10:00:22.116 15435-15488/? W/System.err: java.io.FileNotFoundException: http://api.openweathermap.org/data/2.5/forecast?q=London&lang=en&mode=json&appid=2de143494c0b295cca9337e1e96b00e0
01-28 10:00:22.116 15435-15488/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
01-28 10:00:22.116 15435-15488/? W/System.err:     at cz.martykan.forecastie.MainActivity$GetLongTermWeatherTask.doInBackground(MainActivity.java:537)
01-28 10:00:22.116 15435-15488/? W/System.err:     at cz.martykan.forecastie.MainActivity$GetLongTermWeatherTask.doInBackground(MainActivity.java:515)
01-28 10:00:22.116 15435-15488/? W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
01-28 10:00:22.116 15435-15488/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-28 10:00:22.117 15435-15488/? W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
01-28 10:00:22.117 15435-15488/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-28 10:00:22.117 15435-15488/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-28 10:00:22.117 15435-15488/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
01-28 10:00:22.151 15435-15435/? W/System.err: org.json.JSONException: End of input at character 0 of 
01-28 10:00:22.151 15435-15435/? W/System.err:     at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
01-28 10:00:22.151 15435-15435/? W/System.err:     at org.json.JSONTokener.nextValue(JSONTokener.java:97)
01-28 10:00:22.151 15435-15435/? W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:156)
01-28 10:00:22.151 15435-15435/? W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
01-28 10:00:22.151 15435-15435/? W/System.err:     at cz.martykan.forecastie.MainActivity.parseLongTermJson(MainActivity.java:353)
01-28 10:00:22.151 15435-15435/? W/System.err:     at cz.martykan.forecastie.MainActivity$GetLongTermWeatherTask.onPostExecute(MainActivity.java:561)
01-28 10:00:22.151 15435-15435/? W/System.err:     at cz.martykan.forecastie.MainActivity$GetLongTermWeatherTask.onPostExecute(MainActivity.java:515)
01-28 10:00:22.151 15435-15435/? W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:651)
01-28 10:00:22.151 15435-15435/? W/System.err:     at android.os.AsyncTask.-wrap1(AsyncTask.java)
01-28 10:00:22.151 15435-15435/? W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
01-28 10:00:22.151 15435-15435/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-28 10:00:22.151 15435-15435/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
01-28 10:00:22.151 15435-15435/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5466)
01-28 10:00:22.151 15435-15435/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-28 10:00:22.151 15435-15435/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-28 10:00:22.151 15435-15435/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-28 10:00:22.293 2644-13165/? D/NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 107]: Checking http://connectivitycheck.gstatic.com/generate_204 on three.co.uk, connectivitycheck.gstatic.com=216.58.213.174
01-28 10:00:22.296 2644-13165/? D/NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 107]: Proba
```

**Comment by martykan** [comment]
Update it to 0.8
