### ISSUE TITLE
Sometimes, clicking the widget makes forecastie "crash"

### ISSUE THREAD

**Issue by Porkepix** [martykan/forecastie#438]
Here's an `adb logcat -v threadtime`:

```
02-02 13:05:22.908 17598 17598 D AndroidRuntime: Shutting down VM
02-02 13:05:22.909 17598 17598 E AndroidRuntime: FATAL EXCEPTION: main
02-02 13:05:22.909 17598 17598 E AndroidRuntime: Process: cz.martykan.forecastie, PID: 17598
02-02 13:05:22.909 17598 17598 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{cz.martykan.forecastie/cz.martykan.forecastie.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:234)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at java.lang.StringToReal.parseFloat(StringToReal.java:304)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at java.lang.Float.parseFloat(Float.java:306)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at cz.martykan.forecastie.activities.MainActivity.updateTodayWeatherUI(MainActivity.java:472)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at cz.martykan.forecastie.activities.MainActivity.onStart(MainActivity.java:216)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6302)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2427)
02-02 13:05:22.909 17598 17598 E AndroidRuntime: 	... 9 more
02-02 13:05:24.154 17598 17598 I Process : Sending signal. PID: 17598 SIG: 9
02-02 13:05:24.274   914  3897 I ActivityManager: Process cz.martykan.forecastie (pid 17598) has died
```

This sometimes happens when user clicks the widget, Android pop up a message saying that unfortunately Forecastie have stopped, but widget stays here, nothing terrible happens and clicking it again bring into the application.

**Comment by robinpaulson** [comment]
Yeah, this has been noted before, I can't recall the bug number though. Thanks for the logcat, it will help. It's probably related to the data download being interrupted partway through.

**Comment by robinpaulson** [comment]
This is interesting, an NPE:
02-02 13:05:22.909 17598 17598 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference

**Comment by sotpapathe** [comment]
I occasionally experience the same crash.

The crash happens `app/src/main/java/cz/martykan/forecastie/activities`,
line 472, when trying to convert `todayWeather.temperature` (a string) to
float. It appears it happens because the string is empty.

It's value is set in `app/src/main/java/cz/martykan/forecastie/activities`,
line 386, when parsing the JSON data containing today's weather. Is it possible
that a weather report without a temperature was received?

**Comment by robinpaulson** [comment]
> Is it possible that a weather report without a temperature was received?

i don't have a direct answer to that, but we discussed error-checking elsewhere. i'm not sure if OWM supports CRC or parity checks or whatever, i'm sure it will be on the website somewhere. this is probably the best way to find out if we are getting a full load of data or not.

or, we could put in an error check which replaces the blank value with something sane and/or that forces it to check again until a valid value is received

**Comment by robinpaulson** [comment]
#438 would also help here, although that's a big project

**Comment by Jeinzi** [comment]
I just experienced this crash as well. Stacktrace for 1.17.3:
```
FATAL EXCEPTION: main
Process: cz.martykan.forecastie, PID: 10388
java.lang.RuntimeException: Unable to start activity ComponentInfo{cz.martykan.forecastie/cz.martykan.forecastie.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
	at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1068)
	at java.lang.Float.parseFloat(Float.java:459)
	at cz.martykan.forecastie.activities.MainActivity.updateTodayWeatherUI(MainActivity.java:500)
	at cz.martykan.forecastie.activities.MainActivity.onStart(MainActivity.java:234)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6701)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
	... 9 more
```

Running on Galaxy S6 SM-G920F with LineageOS 14.1 (Android 7.1.2) and microG.
