### ISSUE TITLE
App crashes due to network issue

### ISSUE THREAD

**Issue by chihuazhang** [martykan/forecastie#466]
Studies have shown that mobile apps are prone to crashes due to a network issue, mainly because successful network calls return unexpected or no data. And we found that when this app (version 21)'s network returned data is null or empty(JSON format), the app has crashed. the specific crash information is as follows:

> java.lang.RuntimeException: Unable to start activity ComponentInfo{cz.martykan.forecastie/cz.martykan.forecastie.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
	at java.lang.StringToReal.parseDouble(StringToReal.java:263)
	at java.lang.Double.parseDouble(Double.java:301)
	at cz.martykan.forecastie.activities.MainActivity.updateTodayWeatherUI(MainActivity.java:498)
	at cz.martykan.forecastie.activities.MainActivity.onStart(MainActivity.java:183)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
	at android.app.Activity.performStart(Activity.java:6253)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
	... 9 more
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
	at java.lang.StringToReal.parseDouble(StringToReal.java:263)
	at java.lang.Double.parseDouble(Double.java:301)
	at cz.martykan.forecastie.activities.MainActivity.updateTodayWeatherUI(MainActivity.java:498)
	at cz.martykan.forecastie.activities.MainActivity.onStart(MainActivity.java:183)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
	at android.app.Activity.performStart(Activity.java:6253)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by robinpaulson** [comment]
Yes, we've got a few issues in this category (#349 and #438 at least). I'm not sure which studies you're citing, we've talked about the problem briefly here. Perhaps OWM provides a CRC/parity/checksum for their data? I'll close this as it's a dupe, it's linked to the existing issues though.

**Comment by robinpaulson** [comment]
Also, what is version 21? Our latest version is 1.13.5
