### ISSUE TITLE
Find some crashes!

### ISSUE THREAD

**Issue by LvZW1895** [martykan/forecastie#583]
APK Version : 1.17.2
AndroidOS Version = 6.0-9.0
**Description information：**
These crashes happened by accident when I was testing in different devices. I tried to reproduce them and found that they can't be reproduced, but they are real. I hope they can help you to debug.

**Crash 1:**
Long Msg: java.lang.IllegalArgumentException: View=DecorView@c78088[MainActivity] not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:546)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:439)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:208)
	at android.app.Dialog.dismissDialog(Dialog.java:517)
	at android.app.Dialog.dismiss(Dialog.java:500)
	at cz.martykan.forecastie.tasks.GenericRequestTask.onPostExecute(GenericRequestTask.java:204)
	at cz.martykan.forecastie.activities.MainActivity$TodayWeatherTask.onPostExecute(MainActivity.java:932)
	at cz.martykan.forecastie.activities.MainActivity$TodayWeatherTask.onPostExecute(MainActivity.java:919)
	at android.os.AsyncTask.finish(AsyncTask.java:696)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:713)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Crash 2:**
Long Msg: java.lang.IllegalArgumentException: Number of rows/columns can't be lesser than 1.
	at com.db.chart.view.ChartView.setGrid(ChartView.java:1423)
	at cz.martykan.forecastie.activities.GraphActivity.humidityGraph(GraphActivity.java:364)
	at cz.martykan.forecastie.activities.GraphActivity.updateGraphs(GraphActivity.java:158)
	at cz.martykan.forecastie.activities.GraphActivity.access$300(GraphActivity.java:42)
	at cz.martykan.forecastie.activities.GraphActivity$4.onCheckedChanged(GraphActivity.java:104)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:176)
	at android.widget.Switch.setChecked(Switch.java:1124)
	at android.widget.Switch.toggle(Switch.java:1119)
	at android.widget.CompoundButton.performClick(CompoundButton.java:137)
	at android.view.View.performClickInternal(View.java:6620)
	at android.view.View.access$3100(View.java:787)
	at android.view.View$PerformClick.run(View.java:26167)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Crash 3:**
Long Msg: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@2086418 for displayid = 0 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:931)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:398)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:129)
	at android.app.Dialog.show(Dialog.java:471)
	at cz.martykan.forecastie.tasks.GenericRequestTask.onPreExecute(GenericRequestTask.java:60)
	at cz.martykan.forecastie.activities.MainActivity$TodayWeatherTask.onPreExecute(MainActivity.java:927)
	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:649)
	at android.os.AsyncTask.execute(AsyncTask.java:596)
	at cz.martykan.forecastie.activities.MainActivity.getTodayWeather(MainActivity.java:319)
	at cz.martykan.forecastie.activities.MainActivity.refreshWeather(MainActivity.java:759)
	at cz.martykan.forecastie.activities.MainActivity$ProvideCityNameTask.onPostExecute(MainActivity.java:1082)
	at cz.martykan.forecastie.activities.MainActivity$ProvideCityNameTask.onPostExecute(MainActivity.java:1040)
	at android.os.AsyncTask.finish(AsyncTask.java:696)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:713)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Crash 4:**
Long Msg: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at cz.martykan.forecastie.activities.MainActivity.updateTodayWeatherUI(MainActivity.java:509)
	at cz.martykan.forecastie.activities.MainActivity.onStart(MainActivity.java:243)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1419)
	at android.app.Activity.performStart(Activity.java:7462)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3388)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Crash 5:**
Long Msg: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b3c462 u0 cz.martykan.forecastie/.notifications.WeatherNotificationService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2082)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by robinpaulson** [comment]
Thanks for reporting these.
